from __future__ import annotations

from .akirabox import (
    AkiraBoxPageParser,
    AkiraBoxProvider,
    akirabox_cookies,
    akirabox_download_href_from_page,
    akirabox_referer_from_page,
    akirabox_request_headers,
    akirabox_storage_url,
)
from .base import Provider, ResolveError, ResolvedDownload
from .buzzheavier import (
    BuzzHeavierPageParser,
    BuzzHeavierProvider,
    buzzheavier_download_href_from_page,
    buzzheavier_file_name_from_page,
    buzzheavier_hx_redirect,
    buzzheavier_page_from_page,
    buzzheavier_redirect_from_fetch_result,
)
from .datanodes import (
    DataNodesDownloadForm,
    DataNodesPageParser,
    DataNodesProvider,
    datanodes_cookies,
    datanodes_download_form_from_html,
    datanodes_download_page_url,
    datanodes_fetch_download_page,
    datanodes_origin,
    datanodes_post_download_url,
    datanodes_request_headers,
)
from .registry import PROVIDERS, provider_for_url
from .transport import add_cookie_header, decode_response_body, http_request
from .utils import (
    cookie_names_for_log,
    expires_at_from_url,
    file_name_from_url,
    html_bool_attr,
    html_from_page,
    html_int_attr,
    normalized_host,
    provider_log,
    safe_url_for_log,
)
from .vikingfile import DownloadLinkParser, VikingFileProvider, download_href_from_page

__all__ = [
    "AkiraBoxPageParser",
    "AkiraBoxProvider",
    "BuzzHeavierPageParser",
    "BuzzHeavierProvider",
    "DataNodesDownloadForm",
    "DataNodesPageParser",
    "DataNodesProvider",
    "DownloadLinkParser",
    "PROVIDERS",
    "Provider",
    "ResolveError",
    "ResolvedDownload",
    "VikingFileProvider",
    "add_cookie_header",
    "akirabox_cookies",
    "akirabox_download_href_from_page",
    "akirabox_referer_from_page",
    "akirabox_request_headers",
    "akirabox_storage_url",
    "buzzheavier_download_href_from_page",
    "buzzheavier_file_name_from_page",
    "buzzheavier_hx_redirect",
    "buzzheavier_page_from_page",
    "buzzheavier_redirect_from_fetch_result",
    "cookie_names_for_log",
    "datanodes_cookies",
    "datanodes_download_form_from_html",
    "datanodes_download_page_url",
    "datanodes_fetch_download_page",
    "datanodes_origin",
    "datanodes_post_download_url",
    "datanodes_request_headers",
    "decode_response_body",
    "download_href_from_page",
    "expires_at_from_url",
    "file_name_from_url",
    "html_bool_attr",
    "html_from_page",
    "html_int_attr",
    "http_request",
    "normalized_host",
    "provider_for_url",
    "provider_log",
    "safe_url_for_log",
]
